import {
  AgentProfile,
  AgentPricing,
  AgentRuntime,
} from "./types";

// Static snapshot of agents for client-side use without fs
export const AGENTS: AgentProfile[] = [
  {
    id: "aider",
    name: "Aider",
    tagline: "Terminal-native AI pair programming that treats git as a first-class citizen. Best for engineers who prefer the command line and want clean, reviewable commits.",
    description: "",
    website: "https://aider.chat",
    repository: "https://github.com/Aider-AI/aider",
    categories: ["Coding", "Terminal", "Open Source"],
    pricing: "Open Source" as AgentPricing,
    runtime: "Local" as AgentRuntime,
    openSource: true,
    multiPlatform: true,
    providerAgnostic: true,
    model: "Model-agnostic",
    platforms: ["CLI"],
    features: ["Git-native editing workflow", "Multi-file edits", "Supports many LLM providers", "Voice coding support", "Architect and editor model modes"],
    releaseYear: 2023,
    company: "Aider AI",
    lastVerified: "2026-06-14",
  },
  {
    id: "bolt",
    name: "Bolt.new",
    tagline: "Prompt-to-full-stack platform from StackBlitz. Spin up React/Node apps with databases, auth, hosting, and analytics from a single conversation.",
    description: "",
    website: "https://bolt.new",
    repository: "https://github.com/stackblitz/bolt.new",
    categories: ["No-Code", "Full-Stack", "Prototyping"],
    pricing: "Freemium" as AgentPricing,
    runtime: "Cloud" as AgentRuntime,
    openSource: false,
    multiPlatform: true,
    providerAgnostic: false,
    model: "Multiple frontier models",
    platforms: ["Web"],
    features: ["Prompt-to-app generation", "Built-in hosting and analytics", "Unlimited databases", "Design system integration", "GitHub and Figma import"],
    releaseYear: 2025,
    company: "StackBlitz",
    lastVerified: "2026-06-15",
  },
  {
    id: "claude-code",
    name: "Claude Code",
    tagline: "Anthropic's terminal coding agent. Best for complex software engineering tasks where deep reasoning and large-context understanding matter more than raw speed.",
    description: "",
    website: "https://docs.anthropic.com/en/docs/claude-code/overview",
    categories: ["Coding", "Terminal", "Proprietary"],
    pricing: "Paid" as AgentPricing,
    runtime: "Hybrid" as AgentRuntime,
    openSource: false,
    multiPlatform: true,
    providerAgnostic: false,
    model: "Claude 4 Sonnet / Opus",
    platforms: ["CLI"],
    features: ["Natural language codebase understanding", "Terminal command execution", "Git integration", "IDE extension support", "Autonomous task planning"],
    releaseYear: 2025,
    company: "Anthropic",
    lastVerified: "2026-06-14",
  },
  {
    id: "cline",
    name: "Cline",
    tagline: "Open-source VS Code extension that runs an autonomous coding agent with bring-your-own-key flexibility. Best for developers who want control over model choice and cost.",
    description: "",
    website: "https://cline.bot",
    repository: "https://github.com/cline/cline",
    categories: ["Coding", "IDE Extension", "Open Source"],
    pricing: "Open Source" as AgentPricing,
    runtime: "Local" as AgentRuntime,
    openSource: true,
    multiPlatform: true,
    providerAgnostic: true,
    model: "Model-agnostic",
    platforms: ["VS Code"],
    features: ["Autonomous file edits and terminal commands", "Bring-your-own API key for any provider", "Browser automation and MCP support", "Git-aware workflow", "Free and MIT-licensed"],
    releaseYear: 2024,
    company: "Cline",
    lastVerified: "2026-06-14",
  },
  {
    id: "cursor",
    name: "Cursor",
    tagline: "AI-first code editor built on VS Code. Best for developers who want an integrated, polished agent experience and are willing to pay for convenience.",
    description: "",
    website: "https://www.cursor.com",
    categories: ["Coding", "IDE", "Proprietary"],
    pricing: "Freemium" as AgentPricing,
    runtime: "Hybrid" as AgentRuntime,
    openSource: false,
    multiPlatform: true,
    providerAgnostic: false,
    model: "Claude 4 Sonnet / GPT-4o / Gemini",
    platforms: ["IDE"],
    features: ["AI-native code editor", "Composer for multi-file edits", "Tab-based code predictions", "Context-aware chat", "VS Code extension compatibility"],
    releaseYear: 2023,
    company: "Anysphere",
    lastVerified: "2026-06-14",
  },
  {
    id: "devin",
    name: "Devin",
    tagline: "Cognition's fully autonomous software engineer. Plans, codes, debugs, and deploys in its own sandboxed cloud workspace with minimal human guidance.",
    description: "",
    website: "https://www.cognition.ai",
    categories: ["Coding", "Full-Stack", "Proprietary"],
    pricing: "Paid" as AgentPricing,
    runtime: "Hybrid" as AgentRuntime,
    openSource: false,
    multiPlatform: true,
    providerAgnostic: false,
    model: "o3-mini",
    platforms: ["Web"],
    features: ["End-to-end project execution", "Sandboxed cloud environment", "Autonomous planning and debugging", "Code review and PR creation", "Long-running tasks"],
    releaseYear: 2024,
    company: "Cognition Labs",
    lastVerified: "2026-06-15",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    tagline: "The AI pair programmer used by millions. Best for teams already embedded in the GitHub ecosystem who want low-friction assistance across the SDLC.",
    description: "",
    website: "https://github.com/features/copilot",
    categories: ["Coding", "IDE", "Proprietary"],
    pricing: "Freemium" as AgentPricing,
    runtime: "Hybrid" as AgentRuntime,
    openSource: false,
    multiPlatform: true,
    providerAgnostic: false,
    model: "GPT-4o / Claude 4 Sonnet",
    platforms: ["IDE", "CLI"],
    features: ["Inline code completion", "Copilot Chat", "Agent mode for multi-step tasks", "IDE integration", "GitHub-native workflows"],
    releaseYear: 2021,
    company: "GitHub / Microsoft",
    lastVerified: "2026-06-14",
  },
  {
    id: "hermes-agent",
    name: "Hermes Agent",
    tagline: "Self-improving autonomous agent from Nous Research that learns reusable skills, keeps persistent memory, and runs across 20+ providers and messaging platforms.",
    description: "",
    website: "https://hermes-agent.nousresearch.com",
    repository: "https://github.com/NousResearch/hermes-agent",
    categories: ["Coding", "General Purpose", "Multi-Platform", "Open Source"],
    pricing: "Open Source" as AgentPricing,
    runtime: "Hybrid" as AgentRuntime,
    openSource: true,
    multiPlatform: true,
    providerAgnostic: true,
    model: "Model-agnostic",
    platforms: ["CLI", "Telegram", "Discord", "Slack", "Email", "IDE"],
    features: ["Self-improving skills system", "Persistent cross-session memory", "20+ LLM providers", "Messaging gateway for 10+ platforms", "Cron scheduling and webhooks", "MCP server integration"],
    releaseYear: 2025,
    company: "Nous Research",
    lastVerified: "2026-06-15",
  },
  {
    id: "lovable",
    name: "Lovable",
    tagline: "Prompt-first app builder for founders and designers. Generates React/Node apps with a managed cloud backend, real-time collaboration, and agentic refinement.",
    description: "",
    website: "https://lovable.dev",
    categories: ["No-Code", "Full-Stack", "Startups"],
    pricing: "Freemium" as AgentPricing,
    runtime: "Cloud" as AgentRuntime,
    openSource: false,
    multiPlatform: true,
    providerAgnostic: false,
    model: "Multiple frontier models",
    platforms: ["Web"],
    features: ["Prompt-first app generation", "Built-in Lovable Cloud backend", "Real-time collaboration", "Agentic autonomous editing mode", "AI connectors (Perplexity, ElevenLabs, Firecrawl)"],
    releaseYear: 2025,
    company: "Lovable",
    lastVerified: "2026-06-15",
  },
  {
    id: "microsoft-scout",
    name: "Microsoft Scout",
    tagline: "Always-on autonomous desktop agent for Windows and macOS. Acts across files, browser, and Microsoft 365 with human approval gates and enterprise governance.",
    description: "",
    website: "https://www.microsoft.com/en-us/scout",
    categories: ["Enterprise", "Desktop Automation", "Microsoft 365"],
    pricing: "Paid" as AgentPricing,
    runtime: "Hybrid" as AgentRuntime,
    openSource: false,
    multiPlatform: true,
    providerAgnostic: false,
    model: "Proprietary",
    platforms: ["Windows", "macOS", "Microsoft 365"],
    features: ["Always-on desktop autopilot", "Cross-app task execution", "Entra identity with human approval gates", "Purview governance integration", "File-system and browser automation"],
    releaseYear: 2026,
    company: "Microsoft",
    lastVerified: "2026-06-15",
  },
  {
    id: "openai-codex",
    name: "OpenAI Codex CLI",
    tagline: "OpenAI's terminal coding agent with strong sandboxed execution. Best for developers who trust OpenAI's models and want an agent that can run and verify code safely.",
    description: "",
    website: "https://github.com/openai/codex",
    repository: "https://github.com/openai/codex",
    categories: ["Coding", "Terminal", "Proprietary"],
    pricing: "Freemium" as AgentPricing,
    runtime: "Hybrid" as AgentRuntime,
    openSource: false,
    multiPlatform: true,
    providerAgnostic: false,
    model: "codex-1 / o4-mini",
    platforms: ["CLI"],
    features: ["Agentic code editing", "Sandboxed code execution", "Natural language debugging", "Git-aware operations", "Multi-file reasoning"],
    releaseYear: 2025,
    company: "OpenAI",
    lastVerified: "2026-06-14",
  },
  {
    id: "openclaw",
    name: "OpenClaw",
    tagline: "Personal AI assistant that runs on your own machines and answers on the messaging channels you already use. Built for privacy, model freedom, and multi-agent fleets.",
    description: "",
    website: "https://openclaw.ai",
    repository: "https://github.com/openclaw/openclaw",
    categories: ["Personal Assistant", "Multi-Agent", "Open Source"],
    pricing: "Open Source" as AgentPricing,
    runtime: "Hybrid" as AgentRuntime,
    openSource: true,
    multiPlatform: true,
    providerAgnostic: true,
    model: "Model-agnostic",
    platforms: ["CLI", "API", "Web dashboard", "Telegram", "Discord", "Slack", "WhatsApp", "Signal", "iMessage"],
    features: ["Local-first architecture", "Multi-agent fleet with isolated workspaces", "20+ messaging channels", "Skill ecosystem via ClawHub", "Granular tool policies and sandboxing", "Model-agnostic provider support"],
    releaseYear: 2024,
    company: "OpenClaw Community",
    lastVerified: "2026-06-15",
  },
  {
    id: "openhands",
    name: "OpenHands",
    tagline: "Community-driven open-source platform for autonomous software engineering. Model-agnostic, sandboxed, and built for research and practical tasks.",
    description: "",
    website: "https://www.all-hands.dev",
    repository: "https://github.com/All-Hands-AI/OpenHands",
    categories: ["Coding", "Research", "Open Source"],
    pricing: "Open Source" as AgentPricing,
    runtime: "Hybrid" as AgentRuntime,
    openSource: true,
    multiPlatform: true,
    providerAgnostic: true,
    model: "Model-agnostic",
    platforms: ["Web", "CLI", "API"],
    features: ["Model-agnostic via LiteLLM", "Sandboxed execution environment", "Multi-step planning and debugging", "Extensible agent architecture", "Active open-source community"],
    releaseYear: 2024,
    company: "All Hands AI",
    lastVerified: "2026-06-15",
  },
  {
    id: "replit-agent",
    name: "Replit Agent",
    tagline: "Autonomous coding agent inside Replit that builds, tests, and deploys full-stack apps from chat — with subagents, long sessions, and built-in hosting.",
    description: "",
    website: "https://replit.com",
    categories: ["No-Code", "Full-Stack", "Education"],
    pricing: "Freemium" as AgentPricing,
    runtime: "Cloud" as AgentRuntime,
    openSource: false,
    multiPlatform: true,
    providerAgnostic: false,
    model: "Proprietary",
    platforms: ["Web"],
    features: ["End-to-end build-test-deploy in one workspace", "Autonomous Agent 3 sessions up to 200 minutes", "Economy, Power, and Turbo effort modes", "Subagents for specialized tasks", "Built-in hosting and custom domains"],
    releaseYear: 2025,
    company: "Replit",
    lastVerified: "2026-06-15",
  },
  {
    id: "v0",
    name: "v0",
    tagline: "Vercel's generative UI tool. Turns text prompts into production-grade React and Next.js interfaces, then deploys to Vercel in one click.",
    description: "",
    website: "https://v0.dev",
    categories: ["No-Code", "Frontend", "Next.js"],
    pricing: "Freemium" as AgentPricing,
    runtime: "Cloud" as AgentRuntime,
    openSource: false,
    multiPlatform: true,
    providerAgnostic: false,
    model: "Multiple frontier models",
    platforms: ["Web"],
    features: ["Prompt-to-React UI generation", "One-click deploy to Vercel", "Design system and component library imports", "Full-stack Next.js app support", "Agentic workflow support"],
    releaseYear: 2024,
    company: "Vercel",
    lastVerified: "2026-06-15",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    tagline: "AI-native IDE by Codeium with cascade workflows that combine autonomous agents and inline editing in a single interface.",
    description: "",
    website: "https://windsurf.com",
    categories: ["Coding", "IDE", "Proprietary"],
    pricing: "Freemium" as AgentPricing,
    runtime: "Hybrid" as AgentRuntime,
    openSource: false,
    multiPlatform: true,
    providerAgnostic: false,
    model: "Model-agnostic",
    platforms: ["Windows", "macOS", "Linux"],
    features: ["Cascade agentic workflows", "AI-native editor", "Multi-file reasoning", "Inline predictions", "Terminal integration"],
    releaseYear: 2024,
    company: "Codeium",
    lastVerified: "2026-06-15",
  },
  {
    id: "zed",
    name: "Zed",
    tagline: "Rust-native, GPU-accelerated code editor with real-time multiplayer editing, open-weight edit prediction, and bring-your-own-key AI agents.",
    description: "",
    website: "https://zed.dev",
    repository: "https://github.com/zed-industries/zed",
    categories: ["Coding", "IDE", "Collaborative", "Open Source"],
    pricing: "Freemium" as AgentPricing,
    runtime: "Local" as AgentRuntime,
    openSource: true,
    multiPlatform: true,
    providerAgnostic: true,
    model: "Model-agnostic / Zeta2.1",
    platforms: ["macOS", "Linux", "Windows"],
    features: ["Native Rust GPU-accelerated editor", "Real-time multiplayer editing", "Open-weight Zeta2.1 edit prediction", "Bring-your-own-key AI", "Voice channels and shared buffers"],
    releaseYear: 2024,
    company: "Zed Industries",
    lastVerified: "2026-06-15",
  },
];

export const AGENT_CATEGORIES: string[] = Array.from(
  new Set(AGENTS.flatMap((a) => a.categories))
).sort();

export const AGENT_RUNTIMES: AgentRuntime[] = ["Local", "Cloud", "Hybrid"];

export const AGENT_PRICINGS: AgentPricing[] = [
  "Free",
  "Paid",
  "Freemium",
  "Open Source",
];
