export const agentNameColors: Record<string, string> = {
  "OpenClaw": "text-cyan",
  "Claude Code": "text-rose",
  "Cursor": "text-violet",
  "Aider": "text-emerald",
  "Cline": "text-cyan",
  "Devin": "text-amber",
  "GitHub Copilot": "text-crimson",
  "Hermes Agent": "text-copper",
  "Lovable": "text-magenta",
  "Microsoft Scout": "text-blue",
  "OpenAI Codex CLI": "text-tangerine",
  "OpenHands": "text-lime",
  "Replit Agent": "text-indigo",
  "Bolt.new": "text-teal",
  "v0": "text-foreground",
  "Windsurf": "text-gold",
  "Zed": "text-cyan",
};
